settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: zerotrust # unique identifier
    name: Zerotrust
    description: 'Cloudflare Zerotrust Remote' # default=empty
    url: 'https://yacd.sandbox.us.kg/ui/meta' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: drive
    name: Drive
    description: 'Google Drive Index'
    url: 'https://drive.do11ars.us.kg'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: vless
    name: Vless
    description: 'Workers Server'
    url: 'https://gcp.sandbox.us.kg'
    method: GET
    expectStatus: 200
    linkable: false
